name: Lint and Test

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint
        run: docker compose run --rm lint

      - name: Test
        run: docker compose run --rm tests

      - name: Shellcheck
        run: docker compose run --rm shellcheck